[green_agent]
agentbeats_id = ""
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bbe04-29c1-7863-a5b3-d9481fa7cf14"
name = "agent"
env = {OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}"}


[config]
num_trials = 3
# Add your assessment config here
